version: '3.8'

services:
  frontend:
    build:
      context: frontend
      dockerfile: ../infra/local/frontend/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host 0.0.0.0
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./infra/local/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/app
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: backend
      dockerfile: ../infra/local/backend/Dockerfile
    volumes:
      - ./backend:/app
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_app
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data: